sudo: required
language: node_js
node_js: "stable"

env:
  - NO_PROXY="localhost, 0.0.0.0/4201, 0.0.0.0/9876"

addons:
  hosts:
    - travis.dev
  chrome: stable

notifications:
  email: false

before_install:
  - stty cols 80

script:
  # Main repo
  - if [ $TRAVIS_PULL_REQUEST = "false" ]; then npm run test-remote; fi
  # Forks (Travis blocks encrypted environment variables, so no remote tests)
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then npm test; fi

after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
